name: Build and Deploy to S3

on:
  pull_request:
    branches:
      - develop

jobs:
  check-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v2
        with: 
          repository: Savimbi/dorna-infra
          path: infra-repo
      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1 
          
      - name: Init terraform
        working-directory: infra-repo
        run: |
          terraform init
          terraform apply -auto-approve
        
  deploy-app:
    runs-on: ubuntu-latest
    needs: check-infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'  # Specify your Node.js version here

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Run TypeScript Compiler
        run: npm run tsc --noEmit # Ensure you have a script in package.json for TypeScript check

      # Optional: Run unit tests if you have any configured
      - name: Run Tests
        run: npm test

      # Upload Built Files to S3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Change to your desired region

      - name: Sync built files to S3
        run: |
          aws s3 sync ./out s3://bigbiipwebfront --delete
        env:
          AWS_DEFAULT_REGION: us-west-1
